In [2]:
import pandas as pd
import numpy as np

In [7]:
from sklearn.neural_network import MLPRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression

In [8]:
from sklearn.model_selection import train_test_split

In [5]:
import tensorflow as tf

In [29]:
data = pd.read_csv("regression.csv")

In [30]:
data

       time  people_num  normal  fast_4  fast_6  confuse_num
0         1           1       0       0       0        0.000
1         1           1       0       0       0        0.000
2         1           1       0       0       0        0.000
3         1           1       0       0       0        0.000
4         1           1       0       0       0        0.000
...     ...         ...     ...     ...     ...          ...
29699     8       66710      12       0      21        2.505
29700     8       67230      12       0      21        2.524
29701     8       68383      12       0      21        2.568
29702     8       70744      12       0      21        2.656
29703     8       71523      12       0      21        2.685

[29704 rows x 6 columns]

In [31]:
y = data.iloc[:, 5:6]

In [32]:
X = data.iloc[:, 0:5]

In [18]:
X.dtypes

time          int64
people_num    int64
normal        int64
fast_4        int64
fast_6        int64
dtype: object

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1)

In [28]:
np.nan_to_num(y)

array([[1.999],
       [2.316],
       [2.568],
       ...,
       [1.598],
       [0.989],
       [0.214]])

In [72]:
mlp = MLPRegressor(hidden_layer_sizes=(3, 3, 3, 3),
                   activation='relu', 
                   solver='adam',
                   learning_rate='adaptive',
                   max_iter=2000,
                   learning_rate_init=0.0001,
                   alpha=0.01)

In [73]:
mlp.fit(X_train, y_train)

D:\ProgramData\Anaconda3\envs\tensor1.2\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:1321: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

MLPRegressor(activation='relu', alpha=0.01, batch_size='auto', beta_1=0.9,
             beta_2=0.999, early_stopping=False, epsilon=1e-08,
             hidden_layer_sizes=(3, 3, 3, 3), learning_rate='adaptive',
             learning_rate_init=0.0001, max_iter=2000, momentum=0.9,
             n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
             random_state=None, shuffle=True, solver='adam', tol=0.0001,
             validation_fraction=0.1, verbose=False, warm_start=False)

In [74]:
mlp.score(X_train, y_train)

0.8964823550400527

In [77]:
mlp.score(X_test, y_test)

0.9019416898498801

In [75]:
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [78]:
lr.score(X_test, y_test)

0.8009202932322123

In [76]:
lr.score(X_train, y_train)

0.8090697907930933